### ISSUE TITLE
Несколько вопросов?

### ISSUE THREAD

**Issue by wokster** [demisang/yii2-image-uploader#1]
1. Зачем такая вложенность и почему нет возможности ее отключить?
2. Почему вместо 3-х дефолтных картинок нельзя использовать одну svg? 
3. Пока не заменил это:
   shell_exec('chmod -R 0777 ' . $path . $DS . $dirs[0] . $DS . '*');
   на это:
   FileHelper::createDirectory($full_path, 0777, true);
   творились чудеса и сказки
4. Почему нельзя настроить вместо случайного названия, хеширование md5($this->id.$size.$secret)?

**Comment by demisang** [comment]
Не думал, что кто-нибудь, кроме меня, использует это расширение :)
Что-то действительно следует переписать, многое осталось после миграции с Yii1, то расширение я ещё 3 года назад написал и не улучшал с тех пор.

1. По поводу вложенности: я не вижу ничего страшного в этом, 4 уровня с max 10 директорий на каждом. Можно было бы именовать директории в формате текущей даты, но я решил сделать так, как оно есть сейчас.

2. По поводу SVG я не знаю... наверное возникнут проблемы при сохранении изображения в браузере("сохранить изображение как..."), и я не представляю как можно конвертировать формы jpg,png,gif в svg без потери вида. Тогда бы все так делали :)

3. У меня и на винде и на ubuntu не возникало никаких чудес :) Но я согласен, надо бы замненить этот участок.

4. А какая разница между uniqid() и md5() в плане имени?) Что одно, что другое читабельности не добавляют.

**Comment by wokster** [comment]
Хорошее расширение, но надо доработать
1. удобно когда фото хранится web/папкаСФОТО/модель/id/размер/фото.jpg
2.Я имел ввиду дефолтные фото, которые берутся, когда нет фото. Их три, а можно иметь 1 в svg, так как svg не имеет размера. Например, фотоаппрат или надпись "нет фото".
3. Винда7+openserver+apache. Создаются пустые папки 7770, -w, -s и т.д.
4. Юник надо хранить в базе. А md5 можно сформировать зная id и секрет. Соответственно брать из папки не храня в базе имя вообще. По такому же принципу в название фото можно и размер зашифровать. В результате можно иметь папке images/post/ а в ней куча фото с разными размерами и id.

**Comment by demisang** [comment]
1. У файловых систем есть лимит на количество файлов/каталогов в одном каталоге, т.о. в одной директории рекомендуется хранить до 1 000 файлов/каталогов, есть небольшой [пруф](http://habrahabr.ru/post/70147), там на примере были директории с 20к файлов в одной директории и по 3 секунды файловая система открывала такие файлы.
Поэтому лучше распределять файлы по случайным директориям.
2. Тут полностью согласен, я займусь этим.
3. Исправлю.
4. С одной стороны это было бы удобно, но боюсь такая магия будет вводить людей в заблуждение :) И со случайными директориями это будет несовместимо.
