### ISSUE TITLE
Provide model behavior to delete image on disk

### ISSUE THREAD

**Issue by maxxer** [demisang/yii2-image-uploader#10]
Provide a behavior to be attached to the model which deletes the image when the model is deleted

**Comment by demisang** [comment]
It's already works.
`demi\image\ImageUploaderBehavior` use `\yii\db\BaseActiveRecord::EVENT_AFTER_DELETE` when model deleted - images also delete in `\demi\image\ImageUploaderBehavior::deleteImage`

**Comment by maxxer** [comment]
oh sorry. I'll check, thanks
