### ISSUE TITLE
How Passing ActiveRecord attributes to its behavior?

### ISSUE THREAD

**Issue by ISergeyV** [demisang/yii2-image-uploader#11]
I need that the photos be stored in different folders
EXAMPEL
'savePathAlias' => '@frontend/web/images/products/' . $model->id,

**Comment by demisang** [comment]
По-умолчанию изображения сохраняются в рандомные директории вложенностью три уровня, например:
`/images/products/3/6/1/5a7399224b690.jpg`
т.е.
`$savePathAlias + /<random int 0-9>/<random int 0-9>/<random int 0-9> / <image files>`
Это уже обсуждалось в других issue, сделано так, чтобы защитить сайт от парсинга, а так же чтобы сервер не страдал от слишком большого количества директорий или большого количества файлов в одной директории.

Если всё же требуется сделать так, как хочется, то можно без проблем отнаследоваться от `\demi\image\ImageUploaderBehavior` и перегрузить метод:
public static function getRandomDir($path)
{
    // Вместо набора случайных директорий возвращаем ничего
    return '';
}

protected function uploadImage(\yii\web\UploadedFile $image)
{
    // Моделька, к которой подключено поведение
    $owner = $this->owner;
    // Изменяем путь для сохранения
    $this->_savePathAlias = "@frontend/web/images/products/{$owner->id}";

    return parent::uploadImage($image);
}

**Comment by ISergeyV** [comment]
Большое спасибо за столь полный ответ!
