### ISSUE TITLE
Does widget can work with few images?

### ISSUE THREAD

**Issue by pistol88** [demisang/yii2-image-uploader#7]
I want to load and crop few images for one model. I see it's don't possible at now, but mb you have an ideas or practice for do it?

**Comment by demisang** [comment]
It would be cool, but I want to leave this extension simple.

I can tell you how I usually implement this functionality:
Project - primary model (table `projects`).
ProjectImage - project images (table `projectImages`).

I use this widget for upload few images: https://github.com/2amigos/yii2-file-upload-widget
It's created new ProjectImage item for each image, and my behavior attached to this model - profit :)
