### ISSUE TITLE
Add method to obtain original image

### ISSUE THREAD

**Issue by maxxer** [demisang/yii2-image-uploader#9]
I see on disk the original uploaded image is saved as `xxxx_origina.jpg`. it would be nice to be able to obtain it

**Comment by demisang** [comment]
Complete.
do `composer update` and use:
```php
$model->originalImagePath;
// or identical:
$model->getOriginalImagePath();
// or:
$model->getImageBehavior()->getOriginalImagePath();
```

**Comment by maxxer** [comment]
great, thanks.

worth documenting ;)
